apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-quartz
  labels:
    app: demo-quartz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-quartz
  template:
    metadata:
      labels:
        app: demo-quartz
    spec:
      containers:
        - name: demo-quartz
          image: gcr.io/my-blog-454607/demo-quartz:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/quartz_demo
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
