apiVersion: v1
kind: Service
metadata:
  name: demo-quartz-service
spec:
  selector:
    app: demo-quartz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # GKE sẽ tự tạo 1 external IP để truy cập app
