name: Deploy web to GKE

on:
  push:
    branches:
      - main
      - demo-quartz-JDBC-JobStore
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: True
    steps:
      # Checkout mã nguồn
      - name: Checkout source code
        uses: actions/checkout@v3
      # Xác thực với Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}
      # Cài đặt Google Cloud SDK và gke-gcloud-auth-plugin
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-blog-454607
          install_components: gke-gcloud-auth-plugin
      # Cấu hình Docker để đẩy image lên GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet
      # Kết nối với GKE cluster
      - name: Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials demo-quartz-cluster --zone asia-southeast1-b --project my-blog-454607
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin' # <--- phần bị thiếu
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Build and Push Docker image
        run: |
          IMAGE=gcr.io/my-blog-454607/demo-quartz:latest
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/postgres-secret.yaml
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl apply -f k8s/postgres-service.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
